### PR TITLE
Also target netstandard2.0

### LINKED ISSUE #6: Support for .Net Framework 4.8
My team uses EntityFrameworkCore 3.1.12 which supports .net 4.8  without any issues.
I see how ever that entity-framework-core3-mock does not support 4.8 and cannot be used.
Is there any way around this?

### PR DESCRIPTION
**Pull request by huysentruitw**
Fixes #6

### CODE REVIEW

**Comment by duhowise** [comment]
image
I think efcore 3.o requires netstandard 2.1 and above no?

**Comment by huysentruitw** [comment]
Correct, that's why I needed to update to 3.1.12, which seems to target .NET Standard 2.0.

Sorry I'm going a bit quick over this issue, but I think it should work. Trust me 😉

**Comment by duhowise** [comment]
Thank you I'll check and get back

**Comment by duhowise** [comment]
Update:

```
 var options = new DbContextOptionsBuilder<CoreERPDB>()
                .UseInMemoryDatabase(Guid.NewGuid().ToString())
                .EnableSensitiveDataLogging();

     var       mockCoreERPDB = new DbContextMock<CoreERPDB>(options);
```

fails with error message:

```
 Message: 
    Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: CoreERPDB
    Could not find a constructor that would match given arguments:
    Microsoft.EntityFrameworkCore.DbContextOptions`1[Microsoft.EntityFrameworkCore.DbContext]
```

**Comment by duhowise** [comment]
I got this resolved by adding a non generic ```DbContextOptions``` and the issue was resolved

**Comment by duhowise** [comment]
> 
> 
> Update:
> 
> ```
>  var options = new DbContextOptionsBuilder<CoreERPDB>()
>                 .UseInMemoryDatabase(Guid.NewGuid().ToString())
>                 .EnableSensitiveDataLogging();
> 
>      var       mockCoreERPDB = new DbContextMock<CoreERPDB>(options);
> ```
> 
> fails with error message:
> 
> ```
>  Message: 
>     Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: CoreERPDB
>     Could not find a constructor that would match given arguments:
>     Microsoft.EntityFrameworkCore.DbContextOptions`1[Microsoft.EntityFrameworkCore.DbContext]
> ```

I got this resolved by adding a non generic ```DbContextOptions``` and the issue was resolved

**Comment by duhowise** [comment]
Thanks @huysentruitw for all the help!

**Comment by huysentruitw** [comment]
You're welcome!

**Pull request merged**
